### ISSUE TITLE
От моста нет ответа. 

### ISSUE THREAD

**Issue by igerka** [sprut666666/com.sprut.homekit2#10]
На ровном месте снова отвалился мост. 
 Перезагрузка не помогает. 

![5e9dbe95-dde9-46ea-9d3d-3f3127b54541](https://user-images.githubusercontent.com/38116628/51932430-d9dcad80-2407-11e9-9fdf-384436f60305.png)

Логи:

20:50:43 | Info Update: Воздухоочиститель measure_temperature: 22.6 new: 22.5
-- | --
20:48:43 | Info Update: Воздухоочиститель measure_humidity: 50 new: 51
20:48:43 | Info Update: Воздухоочиститель measure_temperature: 22.5 new: 22.6
20:47:42 | Info Update: Воздухоочиститель measure_temperature: 22.6 new: 22.5
20:46:42 | Info Update: Воздухоочиститель measure_temperature: 22.5 new: 22.6
20:45:42 | Info Update: Воздухоочиститель measure_humidity: 51 new: 50
20:45:15 | Info 3ae47dd3-3864-4ec6-9b17-8d89207b6795 - device found.
20:45:15 | Success 561334b5-d912-48cd-8c50-5155aae31a12 is added!
20:45:15 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
20:45:15 | Info Гардероб свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"561334b5-d912-48cd-8c50-5155aae31a12","name":"Гардероб свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"6d7c87b2-4436-4fb9-9b26-d3e5bff64a89","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-29T17:24:02.490Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:561334b5-d912-48cd-8c50-5155aae31a12","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"ml5q4rk8jmzijm0","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b200d00025120a2b0b2b0b2b0b2b0b2a0b2b0b2b0b2b0b2b0b2a2512251125110b2b25110b2b0b2b0b2b25110b2b0b2b0a2b0b2b0b00019225110b2b0b2b0b2b0b2b0a2b0b2b0b2b0b2b0b2a0b2b2512251125110b2b25110b2b0b2b0b2b25110b2b0b2a0b2b0b2b0b00019225110b2b0b2b0b2b0a2b0b2b0b2b0b2b0b2b0b2b0b2a2512251125110b2b25110b2b0b2b0b2b25110b2b0a2b0b2b0b2b0b00019225110b2b0b2b0a2c0a2b0b2b0b2b0b2b0a2c0a2b0b2b2511261125110b2b25110b2b0b2b0a2b25120a2c0a2b0b2b0b2b0b0005dc0000000000000000","false":"b2009c0025110b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2a0c2a0b2b2511261125110b2a26110b2b0b2a0c2a25110b2b0b2b0b2b25110b00019126110b2a0c2a0b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2a2512251125110b2b25110c2a0b2b0b2a26110b2b0b2a0b2b25110b00019226100c2a0b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2b0b2a2610261125110b2b25110b2b0b2a0c2a26110b2a0b2b0b2b25110b0005dc000000000000000000000000"}}}
20:45:15 | Success 561334b5-d912-48cd-8c50-5155aae31a12 is start added!
20:45:15 | Info 561334b5-d912-48cd-8c50-5155aae31a12 - device found.
20:45:15 | Success 86041209-87db-4690-be25-286ef5a358ca is added!
20:45:15 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
20:45:15 | Info прихожая свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"86041209-87db-4690-be25-286ef5a358ca","name":"прихожая свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"5e28fd80-edbb-4840-bdb0-a93c1ed0e720","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-26T15:27:55.969Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:86041209-87db-4690-be25-286ef5a358ca","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"9dte9w0urmcokfp","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b210340025120b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0c2c2612261225120b2c25120b2c0b2c0b2c0b2c261225120b2c25120b00019400000000","false":"b20c340025120b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c2512251225130b2c25130b2c0b2c0b2c0b2c2512251225120b2c0b00019400000000"}}}
20:45:15 | Success 86041209-87db-4690-be25-286ef5a358ca is start added!
20:45:15 | Info 86041209-87db-4690-be25-286ef5a358ca - device found.
20:45:15 | Success 52e177a7-410b-4e8c-ad14-6021e4fd7f16 is added!
20:45:14 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
20:45:14 | Info Вентиляция ванная full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"52e177a7-410b-4e8c-ad14-6021e4fd7f16","name":"Вентиляция ванная","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"fc37305d-c833-4b68-a73c-56482f1433bc","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-29T12:48:33.832Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:52e177a7-410b-4e8c-ad14-6021e4fd7f16","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"dt3k6ezg121tjs3","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b21034000c230c230c23240c240c0c230d230c23240c0d230c230c23230c0c000163240c230c240c0c23240c240c0c230d23240c240c0c2300000000","false":"b20e3400240c0c230d23240c0d230c000163240c240c240c0c23240c240c0c230c23240c240c0c230c230d230c23240c240c0d230c230c2300000000"}}}
20:45:14 | Success 52e177a7-410b-4e8c-ad14-6021e4fd7f16 is start added!
20:45:14 | Info 52e177a7-410b-4e8c-ad14-6021e4fd7f16 - device found.
20:45:14 | Success 4f5e8830-a63d-4887-95c8-af714c2bda95 is added!
20:45:14 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"}}
20:45:14 | Info Update: Подсветка кухня onoff: false new: true
20:45:14 | Info Подсветка кухня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"4f5e8830-a63d-4887-95c8-af714c2bda95","name":"Подсветка кухня","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":true,"lastUpdated":"2019-01-29T14:45:09.382Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:4f5e8830-a63d-4887-95c8-af714c2bda95","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"5f78w6utdengvj2","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b200a8000b23240c0b240b230c000167230d230c0b240b230c23230d230c0b24230c0b240b24230c0b240b240b23230c0c230c230b24230c0c23230c0c230b240b000168230c230d0b230c230c23230c230d0b24230c0b240b23240c0b240b240b23240b0c230c230c23230c0c23230c0c240b230b000169220c240c0b240b230c23230d230c0c23230c0c230b24230c0c230c230b24230c0c230c230b24230c0b24230c0c230c230b0005dc","false":"b2063400230d230d0c240c240c24240d230d0c24230d0c240c24240d0c240c240c24240d0c240c240c24230d0c240c240c24240d0c00016a00000000"}}}
20:45:14 | Success 4f5e8830-a63d-4887-95c8-af714c2bda95 is start added!
20:45:14 | Info 4f5e8830-a63d-4887-95c8-af714c2bda95 - device found.
20:45:14 | Success 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 is added!
20:45:14 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"}}
20:45:14 | Info Update: Бар свет onoff: false new: true
20:45:14 | Info Бар свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8","name":"Бар свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":true,"lastUpdated":"2019-01-29T15:15:20.421Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"lhiad10bn0nxszr","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b20d3400230d0c24230d0c24230d230d230d0c24240c0c240c24230d0c240c240c24230d0c240c240c24240c0c240c240c24230d0c00016700000000","false":"b20f34000c24230d0c240c240c24240d0c240c24230d0c240c000168230c0c24240d0c24240d240d240d0c24230d0c240c24240d0c240c2400000000"}}}
20:45:14 | Success 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 is start added!
20:45:14 | Info 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 - device found.
20:45:14 | Success 484ba688-3ab5-4877-b692-0c745dec494a is added!
20:45:14 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
20:45:14 | Info Кухня свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"484ba688-3ab5-4877-b692-0c745dec494a","name":"Кухня свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-27T06:44:53.526Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:484ba688-3ab5-4877-b692-0c745dec494a","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"s0auo7gvs16p9hu","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b2093400230d0c240c24230d0c240c240c24230d0c240c240c24240d0c24240d0c240c240c000167230d0c24230d0c24240d240d230d0c2400000000","false":"b2153400240c240c240c0c23240c0d230d23240c0d230d230c23240c0c240c230d23240c250c0c230d240c230d000167240c0c23240c0c2300000000"}}}
20:45:14 | Success 484ba688-3ab5-4877-b692-0c745dec494a is start added!
20:45:14 | Info 484ba688-3ab5-4877-b692-0c745dec494a - device found.
20:45:14 | Success 28f0f423-6ea0-40fa-80dd-088bec716cc7 is added!
20:45:13 | Info { "message": "Possible EventEmitter memory leak detected. 11 connect_error listeners added. Use emitter.setMaxListeners() to increase limit" }
20:45:13 | Info { "message": "Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit" }
20:45:12 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
20:45:12 | Info Подсветка спальня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"28f0f423-6ea0-40fa-80dd-088bec716cc7","name":"Подсветка спальня","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"24e740c8-8b76-4a0e-ade6-11fa5125c701","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-27T21:27:16.368Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:28f0f423-6ea0-40fa-80dd-088bec716cc7","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"u8p6xp0h9rfn27k","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b21a3400240c240c240c0c23240c240c0d230d23240c240c0c230c230c230c23240c240c0d230c230c23240c0c23240c0c230c230d00016400000000","false":"b20f3400240c240c240c0c23240c240c0d230d23240c240c0c230c230c230c23240c240c0d230c230c23240c240c0c230c230d230c00016300000000"}}}
20:45:12 | Success 28f0f423-6ea0-40fa-80dd-088bec716cc7 is start added!
20:45:12 | Info 28f0f423-6ea0-40fa-80dd-088bec716cc7 - device found.
20:45:12 | Success 82f3fa87-d43d-4e13-babc-653d68e6dfbd is added!
20:45:12 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
20:45:11 | Info Спальня свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"82f3fa87-d43d-4e13-babc-653d68e6dfbd","name":"Спальня свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"24e740c8-8b76-4a0e-ade6-11fa5125c701","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-22T21:59:44.535Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:82f3fa87-d43d-4e13-babc-653d68e6dfbd","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"s2prlp8fa4btinr","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b20b3400240c0c230c230c23240c0c0001640c23240c240c0c230c23230c240c0c230c23240c0c24230c240c0c23240c0c230c230c230c2300000000","false":"b20734000c0001640d23240c240c0c230c23240c240c0c230d23240c0c24240c240c0c23240c0c230c230d230c23240c0c230c23240c0c2300000000"}}}
20:45:11 | Success 82f3fa87-d43d-4e13-babc-653d68e6dfbd is start added!
20:45:11 | Info 82f3fa87-d43d-4e13-babc-653d68e6dfbd - device found.

**Comment by sprut666666** [comment]
Обновить колобок и плагин
