### ISSUE TITLE
Sonoff 4ch

### ISSUE THREAD

**Issue by permadm** [sprut666666/com.sprut.homekit2#11]
Также, как и двойной выключатель, не прокидывается 4-канальный Sonoff
(добавляется неподдерживаемое устройство)

Info sonoff4ch1 full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"7f01f421-4970-45d9-a842-730fed00a655","name":"sonoff4ch1","driverUri":"homey:app:name.klep.sonoff","driverId":"sonoff-tasmota-4ch","zone":"9919ee1e-ffbc-480b-bc4b-77fb047e9e68","icon":null,"iconObj":{"id":"af3a27c6521d6fe9c1588360cc3900ff","url":"/icon/af3a27c6521d6fe9c1588360cc3900ff/icon.svg"},"settings":{"mqttHost":"10.0.0.141","mqttPort":"1883","mqttUser":"user","mqttPassword":"pass","topic":"sonoff4ch1","fallbackTopic":"cmnd/DVES_49167E_fb/","groupTopic":"sonoffs","powerOnState":"3","ledState":"1"},"settingsObj":true,"class":"socket","virtualClass":null,"capabilities":["onoff.1","onoff.2","onoff.3","onoff.4"],"capabilitiesObj":{"onoff.1":{"value":false,"lastUpdated":"2019-01-24T07:20:34.203Z","type":"boolean","getable":true,"setable":true,"title":"Switch 1","desc":null,"units":null,"id":"onoff.1","options":{"title":{"en":"Switch 1","nl":"Schakelaar 1"}}},"onoff.2":{"value":false,"lastUpdated":"2019-01-24T07:20:34.203Z","type":"boolean","getable":true,"setable":true,"title":"Switch 2","desc":null,"units":null,"id":"onoff.2","options":{"title":{"en":"Switch 2","nl":"Schakelaar 2"}}},"onoff.3":{"value":false,"lastUpdated":"2019-01-24T07:20:34.203Z","type":"boolean","getable":true,"setable":true,"title":"Switch 3","desc":null,"units":null,"id":"onoff.3","options":{"title":{"en":"Switch 3","nl":"Schakelaar 3"}}},"onoff.4":{"value":false,"lastUpdated":"2019-01-24T07:20:34.203Z","type":"boolean","getable":true,"setable":true,"title":"Switch 4","desc":null,"units":null,"id":"onoff.4","options":{"title":{"en":"Switch 4","nl":"Schakelaar 4"}}}},"flags":[],"ui":{"quickAction":"onoff.1","components":[{"id":"toggle","capabilities":["onoff.1","onoff.2","onoff.3","onoff.4"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"unavailableMessage":null,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights","Turn all lights on","Turn off all devices","Toggle all lights","Turn all lights on","Turn off all devices","Toggle all lights","Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:7f01f421-4970-45d9-a842-730fed00a655","id":"onoff.1","type":"boolean","title":"Switch 1","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null},{"uri":"homey:device:7f01f421-4970-45d9-a842-730fed00a655","id":"onoff.2","type":"boolean","title":"Switch 2","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null},{"uri":"homey:device:7f01f421-4970-45d9-a842-730fed00a655","id":"onoff.3","type":"boolean","title":"Switch 3","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null},{"uri":"homey:device:7f01f421-4970-45d9-a842-730fed00a655","id":"onoff.4","type":"boolean","title":"Switch 4","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df2620","data":{"id":"84:0D:8E:49:16:7E"}}
--

**Comment by sprut666666** [comment]
готово
