### ISSUE TITLE
Aqara Wall Switches

### ISSUE THREAD

**Issue by fantomnotabene** [sprut666666/com.sprut.homekit2#12]
Homey [2.0.2], HomeKit [3.0.4], двойные акара выключатели (l/ln, через плагин Теда) залетают одной розеткой, которая рулит только левой кнопкой
`Выключатель full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"cf4ddebb-2ce3-4d14-b92d-a17ee5e50e73","name":"Выключатель","driverUri":"homey:app:com.xiaomi-mi","driverId":"ctrl_neutral2","zone":"478cfd92-6475-4214-80d9-27125e39863a","iconObj":{"id":"c37e51656abb2aba588d5d88292cb623","url":"/icon/c37e51656abb2aba588d5d88292cb623/icon.svg"},"settings":{"zb_profile_id":"260","zb_device_id":"6","zb_ieee_addr":"0x00158d0001f482fe","zb_product_id":"lumi.ctrl_neutral2","zb_manufacturer_name":"LUMI"},"settingsObj":true,"class":"socket","virtualClass":"light","capabilities":["onoff","onoff.1"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-02-07T11:40:25.109Z","type":"boolean","getable":true,"setable":true,"title":"Switch 1","desc":null,"units":null,"id":"onoff","options":{"title":{"en":"Switch 1"},"greyout":false}},"onoff.1":{"value":false,"lastUpdated":"2019-02-07T11:37:57.115Z","type":"boolean","getable":true,"setable":true,"title":"Switch 2","desc":null,"units":null,"id":"onoff.1","options":{"title":{"en":"Switch 2"},"greyout":false}}},"flags":["zigbee"],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff","onoff.1"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":true,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights","Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:cf4ddebb-2ce3-4d14-b92d-a17ee5e50e73","id":"onoff","type":"boolean","title":"Switch 1","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null},{"uri":"homey:device:cf4ddebb-2ce3-4d14-b92d-a17ee5e50e73","id":"onoff.1","type":"boolean","title":"Switch 2","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#f57921","data":{"token":"63e53835-e86e-4207-8672-fd1a81f42839"}}`

**Comment by sprut666666** [comment]
готово
