### ISSUE TITLE
Фибаро Роллер шатер прокидывается как 2 устройства

### ISSUE THREAD

**Issue by Stunt4man** [sprut666666/com.sprut.homekit2#14]
Не знаю сюда ли log?:

23:55:18 | Info Update: Штора measure_power: 76.4 new: 0
-- | --
23:55:11 | Info Update: Штора measure_power: 0 new: 76.4
23:55:09 | Info Update: Штора dimdim: 88 new: 0
23:55:09 | Info Штора: set dim = 0.88 => 0
23:55:02 | Info Update: Штора measure_power: 77.1 new: 0
23:55:01 | Info Update: Штора dimdim: 0 new: 88
23:55:01 | Info Update: Штора dim: 0 new: 88
23:55:00 | Info Update: Штора windowcoverings_state: 100 new: 0
23:55:00 | Info Штора: set windowcoverings_state = up => down
23:54:55 | Info Update: Штора measure_power: 0 new: 77.1
23:54:54 | Info Update: Штора windowcoverings_state: 0 new: 100
23:54:52 | Info Штора: set windowcoverings_state = down => up
23:54:42 | Info Bonjour is up
23:54:42 | Success 34b03640-1a28-4c79-9dda-43319fa5dde5 is added!
23:54:42 | Info State in HomeKit: {"windowcoverings_state":{"type":"0000006D-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","ev"],"value":0,"ev":true,"description":"Current Position","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"windowcoverings_stateTargetPosition":{"type":"0000007C-0000-1000-8000-0026BB765291","iid":8,"perms":["pr","pw","ev"],"value":0,"ev":true,"description":"Target Position","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"dimdim":{"type":"0000006D-0000-1000-8000-0026BB765291","iid":10,"perms":["pr","ev"],"value":0,"ev":true,"description":"Current Position","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"dim":{"type":"0000007C-0000-1000-8000-0026BB765291","iid":11,"perms":["pr","pw","ev"],"value":0,"ev":true,"description":"Target Position","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"measure_power":{"type":"00000003-000C-2000-8000-0026BB765291","iid":13,"perms":["pr","ev"],"value":0,"ev":true,"description":"Consumption","format":"float","unit":"W","minValue":0,"maxValue":65535,"minStep":0.01}}
23:54:42 | Info Штора full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"34b03640-1a28-4c79-9dda-43319fa5dde5","name":"Штора","driverUri":"homey:app:com.fibaro","driverId":"FGR-222","zone":"9eb2975d-49ea-4033-8db0-105a3e982117","icon":"/icon.svg","iconObj":{"id":"51f5fb8d1a1cd286c3ad08906208bfe7","url":"/icon/51f5fb8d1a1cd286c3ad08906208bfe7/icon.svg"},"settings":{"reports_type":"0","operating_mode":"1","switch_type":"2","power_level_change":10,"periodic_power_level_reports":3600,"start_calibration":false,"invert_direction":false,"zw_node_id":"44","zw_manufacturer_id":"271","zw_product_type_id":"770","zw_product_id":"4096","zw_secure":"manager.vdevice.drivers.zwavebasic.devicesettings.yes_false","zw_battery":"manager.vdevice.drivers.zwavebasic.devicesettings.yes_false","zw_device_class_basic":"BASIC_TYPE_ROUTING_SLAVE","zw_device_class_generic":"GENERIC_TYPE_SWITCH_MULTILEVEL","zw_device_class_specific":"SPECIFIC_TYPE_CLASS_B_MOTOR_CONTROL","zw_firmware_id":"","zw_wakeup_interval":0,"zw_group_1":"","zw_group_2":"","zw_group_3":"1","zw_configuration_value":"","invertWindowCoveringsDirection":false},"settingsObj":true,"class":"windowcoverings","virtualClass":"curtain","capabilities":["windowcoverings_state","dim","measure_power"],"capabilitiesObj":{"windowcoverings_state":{"value":"down","lastUpdated":"2019-03-05T20:21:36.460Z","type":"enum","getable":true,"setable":true,"title":"Window Coverings State","desc":null,"units":null,"values":[{"id":"up","title":"Up"},{"id":"idle","title":"Idle"},{"id":"down","title":"Down"}],"id":"windowcoverings_state","options":{}},"dim":{"value":0,"lastUpdated":"2019-03-05T20:27:00.875Z","type":"number","getable":true,"setable":true,"title":"Dim level","desc":null,"units":"%","decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"dim","options":{}},"measure_power":{"value":0,"lastUpdated":"2019-03-05T20:27:02.090Z","type":"number","getable":true,"setable":false,"title":"Power","desc":"Power in Watt (W)","units":"W","decimals":2,"chartType":"stepLine","id":"measure_power","options":{}}},"flags":["zwave"],"ui":{"components":[{"id":"slider","capabilities":["dim"]},{"id":"ternary","capabilities":["windowcoverings_state"]},{"id":"sensor","capabilities":["measure_power"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":true,"speechExamples":["Open the window coverings","Dim all lights to 50%","Set My Light to full brightness"],"images":[],"insights":[{"uri":"homey:device:34b03640-1a28-4c79-9dda-43319fa5dde5","id":"measure_power","type":"number","title":"Power","titleTrue":null,"titleFalse":null,"units":"W"}],"color":"#000000","data":{"token":"29a13747-20f7-4a0c-9ad3-aceb6fb8c2a5"}}
23:54:42 | Success 34b03640-1a28-4c79-9dda-43319fa5dde5 is start added!
23:53:39 | Info Bonjour is up
23:53:38 | Info TCP Server Listening on 8091
23:53:38 | Info HTTP Server Listening on 41159
23:53:37 | Success homey.json = {"CCN":18,"pairings":{"4A03A3F7-454A-4F05-AA9A-A096358DA8A7":{"publicKey":"f55f57c404dd6f758f687696b7b62a8eaffc26d1e6393a56dc0bdf3d6fc7283c","isAdmin":true},"49B4D387-F071-4EE3-8548-5D1AF6FC3B08":{"publicKey":"44765ce9704ec62d77db83a17ede9618a8caf632ea5c2301956610e654c633ff","isAdmin":false}},"publicKey":"d89fb0e349f6205980a753c5206aefc8e6aba63f16ef507261d59a86ddd68084","privateKey":"2a694874af4e4d70eaaff436a44e5a8987901ed574c970840cdfbb27466cd1f4d89fb0e349f6205980a753c5206aefc8e6aba63f16ef507261d59a86ddd68084","UUIDMap":{"lastAssignedID":7,"6C:AD:F8:04:D5:F3":1,"1BBA3B12-5D8F-4F41-8096-3CE2E7A98E35":2,"B7AA369C-F0CF-4677-9505-FE9369C4817C":0,"13C292DC-F319-47CD-BEAB-9B02A5CEA8C2":4,"B497DCE1-B0B7-4050-B58B-05F5B52CEEF8":0,"34B03640-1A28-4C79-9DDA-43319FA5DDE5":0,"8BF1237D-53A4-4115-9A7B-1D9989BDFB1B":0}}
23:53:37 | Success Homekit server started.
23:53:37 | Success { "1bba3b12-5d8f-4f41-8096-3ce2e7a98e35": { "group": true, "accessory": false, "pairedСlass": "light", "pairedCapabilities": { "onoff": "onoff", "dim": "dim", "light_hue": "light_hue", "light_saturation": "light_saturation", "light_temperature": "light_temperature", "light_mode": "light_mode", "measure_power": "measure_power", "meter_power": "meter_power", "measure_voltage.input1": "measure_voltage.input1", "measure_voltage.input2": "measure_voltage.input2", "measure_voltage.input3": "measure_voltage.input3", "measure_voltage.input4": "measure_voltage.input4" }, "homeKitIDs": { "2": "1bba3b12-5d8f-4f41-8096-3ce2e7a98e35" } }, "13c292dc-f319-47cd-beab-9b02a5cea8c2": { "group": true, "accessory": false, "pairedСlass": "vacuumcleaner", "pairedCapabilities": { "vacuumcleaner_state": "vacuumcleaner_state", "measure_battery": "measure_battery" }, "homeKitIDs": { "4": "13c292dc-f319-47cd-beab-9b02a5cea8c2" } }, "34b03640-1a28-4c79-9dda-43319fa5dde5": { "group": true, "accessory": false, "pairedСlass": "windowcoverings", "pairedCapabilities": { "windowcoverings_state": "windowcoverings_state", "dim": "dim", "measure_power": "measure_power" }, "homeKitIDs": { "8": "34b03640-1a28-4c79-9dda-43319fa5dde5" } } }
23:53:37 | Success 13c292dc-f319-47cd-beab-9b02a5cea8c2 is added!
23:53:37 | Info State in HomeKit: {"vacuumcleaner_state":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"},"measure_battery":{"type":"00000068-0000-1000-8000-0026BB765291","iid":9,"perms":["pr","ev"],"value":100,"ev":true,"description":"Battery Level","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"measure_batteryStatusLowBattery":{"type":"00000079-0000-1000-8000-0026BB765291","iid":11,"perms":["pr","ev"],"value":0,"ev":true,"description":"Status Low Battery","format":"uint8","valid-values":[0,1]}}
23:53:37 | Info Update: Roomba measure_battery: 0 new: 100
23:53:37 | Info Roomba full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"13c292dc-f319-47cd-beab-9b02a5cea8c2","name":"Roomba","driverUri":"homey:app:com.irobot.roomba980","driverId":"roomba980","zone":"1815c884-af06-4d53-a2c1-6f4c77e9eb4e","icon":null,"iconObj":{"id":"9b9b5c033f1e8949828b849a00476be3","url":"/icon/9b9b5c033f1e8949828b849a00476be3/icon.svg"},"settings":{},"settingsObj":false,"class":"vacuumcleaner","virtualClass":null,"capabilities":["vacuumcleaner_state","measure_battery"],"capabilitiesObj":{"vacuumcleaner_state":{"value":"docked","lastUpdated":"2019-03-05T20:53:33.219Z","type":"enum","getable":true,"setable":true,"title":"Vacuum cleaner state","desc":null,"units":null,"values":[{"id":"cleaning","title":"Cleaning"},{"id":"spot_cleaning","title":"Spot cleaning"},{"id":"docked","title":"Docked"},{"id":"charging","title":"Charging"},{"id":"stopped","title":"Stopped"}],"id":"vacuumcleaner_state","options":{}},"measure_battery":{"value":100,"lastUpdated":"2019-03-05T20:53:33.217Z","type":"number","getable":true,"setable":false,"title":"Battery","desc":"Battery charge in percentage (%)","units":"%","decimals":2,"min":0,"max":100,"chartType":"spline","id":"measure_battery","options":{}}},"flags":[],"ui":{"components":[{"id":"picker","capabilities":["vacuumcleaner_state"]},{"id":"battery","capabilities":["measure_battery"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"unavailableMessage":null,"speechExamples":["Start the vacuum cleaner"],"images":[],"insights":[{"uri":"homey:device:13c292dc-f319-47cd-beab-9b02a5cea8c2","id":"measure_battery","type":"number","title":"Battery","titleTrue":null,"titleFalse":null,"units":"%"}],"color":"#dfb920","data":{"mac":"f0:03:8c:53:2c:6e","name":"Roomba","auth":{"username":"3117450410138750","password":":1:1543693592:rONNkgYFWxlT55Ry"}}}
23:53:37 | Success 13c292dc-f319-47cd-beab-9b02a5cea8c2 is start added!
23:53:37 | Info 13c292dc-f319-47cd-beab-9b02a5cea8c2 - device found.
23:53:37 | Success 1bba3b12-5d8f-4f41-8096-3ce2e7a98e35 is added!
23:53:37 | Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"},"dim":{"type":"00000008-0000-1000-8000-0026BB765291","iid":8,"perms":["pr","pw","ev"],"value":11,"ev":true,"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"light_hue":{"type":"00000013-0000-1000-8000-0026BB765291","iid":9,"perms":["pr","pw","ev"],"value":0,"ev":true,"description":"Hue","format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1},"light_saturation":{"type":"0000002F-0000-1000-8000-0026BB765291","iid":10,"perms":["pr","pw","ev"],"value":0,"ev":true,"description":"Saturation","format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"light_temperature":{"type":"000000CE-0000-1000-8000-0026BB765291","iid":11,"perms":["pr","pw","ev"],"value":499,"ev":true,"description":"Color Temperature","format":"uint32","minValue":140,"maxValue":500,"minStep":1},"measure_power":{"type":"00000003-000C-2000-8000-0026BB765291","iid":12,"perms":["pr","ev"],"value":0,"ev":true,"description":"Consumption","format":"float","unit":"W","minValue":0,"maxValue":65535,"minStep":0.01},"meter_power":{"type":"00000005-000C-2000-8000-0026BB765291","iid":13,"perms":["pr","ev"],"value":0.08,"ev":true,"description":"Total Consumption","format":"float","unit":"kWh","minValue":0,"maxValue":65535,"minStep":0.01}}
23:53:37 | Info Update: Лента measure_power: 0 new: 0.08
23:53:37 | Info Update: Лента light_temperature: 140 new: 499
23:53:37 | Info Update: Лента dim: 0 new: 11
23:53:37 | Info Лента full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","name":"Лента","driverUri":"homey:app:com.fibaro","driverId":"FGRGBWM-441","zone":"9eb2975d-49ea-4033-8db0-105a3e982117","icon":"/icon.svg","iconObj":{"id":"51f5fb8d1a1cd286c3ad08906208bfe7","url":"/icon/51f5fb8d1a1cd286c3ad08906208bfe7/icon.svg"},"settings":{"strip_type":"rgbw","rgbw_white_temperature":true,"white_temperature":"ww","calibrate_white":0,"white_saturation":10,"transition_mode":"0","mode1_steps":1,"mode1_time":10,"mode2_range":"64","mode2_transition_time":3,"maximum_brightness":255,"minimum_brightness":2,"input_config_1":"1","input_config_2":"1","input_config_3":"1","input_config_4":"1","save_state":true,"input_threshold":0.5,"watt_report_interval":30,"kwh_threshold":0.1,"color_pallet":"accurate","zw_node_id":"65","zw_manufacturer_id":"271","zw_product_type_id":"2304","zw_product_id":"4096","zw_secure":"manager.vdevice.drivers.zwavebasic.devicesettings.yes_false","zw_battery":"manager.vdevice.drivers.zwavebasic.devicesettings.yes_false","zw_device_class_basic":"BASIC_TYPE_ROUTING_SLAVE","zw_device_class_generic":"GENERIC_TYPE_SWITCH_MULTILEVEL","zw_device_class_specific":"SPECIFIC_TYPE_POWER_SWITCH_MULTILEVEL","zw_firmware_id":"","zw_wakeup_interval":0,"zw_group_1":"","zw_group_2":"","zw_group_3":"","zw_group_4":"","zw_group_5":"1","zw_configuration_value":""},"settingsObj":true,"class":"light","virtualClass":null,"capabilities":["onoff","dim","light_hue","light_saturation","light_temperature","light_mode","measure_power","meter_power","measure_voltage.input1","measure_voltage.input2","measure_voltage.input3","measure_voltage.input4"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-03-05T04:58:23.922Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{"setOnDim":false}},"dim":{"value":0.10999999940395355,"lastUpdated":"2019-03-05T04:57:53.441Z","type":"number","getable":true,"setable":true,"title":"Dim level","desc":null,"units":"%","decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"dim","options":{}},"light_hue":{"value":0,"lastUpdated":"2019-03-05T04:58:23.899Z","type":"number","getable":true,"setable":true,"title":"Hue","desc":null,"units":null,"decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"light_hue","options":{}},"light_saturation":{"value":0,"lastUpdated":"2019-03-05T04:58:23.913Z","type":"number","getable":true,"setable":true,"title":"Color Saturation","desc":null,"units":null,"decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"light_saturation","options":{}},"light_temperature":{"value":0.9968620445826618,"lastUpdated":"2019-02-09T19:47:42.390Z","type":"number","getable":true,"setable":true,"title":"Color Temperature","desc":null,"units":null,"decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"light_temperature","options":{}},"light_mode":{"value":"color","lastUpdated":"2019-03-05T04:57:53.669Z","type":"enum","getable":true,"setable":true,"title":"Light mode","desc":"Switch between Color or Temperature mode","units":null,"values":[{"id":"color","title":"Color"},{"id":"temperature","title":"Temperature"}],"id":"light_mode","options":{}},"measure_power":{"value":0,"lastUpdated":"2019-03-05T04:58:25.054Z","type":"number","getable":true,"setable":false,"title":"Power","desc":"Power in Watt (W)","units":"W","decimals":2,"chartType":"stepLine","id":"measure_power","options":{}},"meter_power":{"value":0.08,"lastUpdated":"2019-03-01T14:32:43.502Z","type":"number","getable":true,"setable":false,"title":"Power Meter","desc":"Power usage in KiloWattHour (kWh)","units":"KWh","decimals":2,"chartType":"spline","id":"meter_power","options":{}},"measure_voltage.input1":{"value":0,"lastUpdated":"2019-03-05T04:58:23.840Z","type":"number","getable":true,"setable":false,"title":"Input 1","desc":"Voltage (V)","units":"V","decimals":2,"chartType":"stepLine","id":"measure_voltage.input1","options":{"title":{"en":"Input 1","nl":"Ingang 1"}}},"measure_voltage.input2":{"value":0,"lastUpdated":"2019-02-28T20:32:31.960Z","type":"number","getable":true,"setable":false,"title":"Input 2","desc":"Voltage (V)","units":"V","decimals":2,"chartType":"stepLine","id":"measure_voltage.input2","options":{"title":{"en":"Input 2","nl":"Ingang 2"}}},"measure_voltage.input3":{"value":0,"lastUpdated":"2019-03-05T04:58:23.922Z","type":"number","getable":true,"setable":false,"title":"Input 3","desc":"Voltage (V)","units":"V","decimals":2,"chartType":"stepLine","id":"measure_voltage.input3","options":{"title":{"en":"Input 3","nl":"Ingang 3"}}},"measure_voltage.input4":{"value":0,"lastUpdated":"2019-03-04T04:55:25.447Z","type":"number","getable":true,"setable":false,"title":"Input 4","desc":"Voltage (V)","units":"V","decimals":2,"chartType":"stepLine","id":"measure_voltage.input4","options":{"title":{"en":"Input 4","nl":"Ingang 4"}}}},"flags":["zwave"],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]},{"id":"slider","capabilities":["dim"]},{"id":"color","capabilities":["light_hue","light_saturation","light_temperature","light_mode"]},{"id":"sensor","capabilities":["measure_power","meter_power","measure_voltage.input1","measure_voltage.input2","measure_voltage.input3","measure_voltage.input4"]}],"componentsStartAt":1},"ready":true,"available":true,"repair":false,"unpair":true,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights","Dim all lights to 50%","Set My Light to full brightness","Turn all lights to blue","Turn My Light to pink","Turn all lights to warm white","Turn My Light to cool white"],"images":[],"insights":[{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null},{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"measure_power","type":"number","title":"Power","titleTrue":null,"titleFalse":null,"units":"W"},{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"meter_power","type":"number","title":"Power Meter","titleTrue":null,"titleFalse":null,"units":"KWh"},{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"measure_voltage.input1","type":"number","title":"Input 1","titleTrue":null,"titleFalse":null,"units":"V"},{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"measure_voltage.input2","type":"number","title":"Input 2","titleTrue":null,"titleFalse":null,"units":"V"},{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"measure_voltage.input3","type":"number","title":"Input 3","titleTrue":null,"titleFalse":null,"units":"V"},{"uri":"homey:device:1bba3b12-5d8f-4f41-8096-3ce2e7a98e35","id":"measure_voltage.input4","type":"number","title":"Input 4","titleTrue":null,"titleFalse":null,"units":"V"}],"color":"#000000","data":{"token":"b4fbc32a-a800-4c33-8434-d84b289c6387"}}
23:53:37 | Success 1bba3b12-5d8f-4f41-8096-3ce2e7a98e35 is start added!
23:53:37 | Info 1bba3b12-5d8f-4f41-8096-3ce2e7a98e35 - device found.
23:53:37 | Success Server config done.
23:53:37 | Success {"bootId":"175f23d5-f49a-443f-8b47-e6556910e5f5","cloudId":"571756657d37c57a0cec81c7","hostname":"Homey","platform":"linux","release":"4.14.15-g81f15bab94","arch":"arm","uptime":433516,"loadavg":[0.89404296875,0.41796875,0.3427734375],"totalmem":511922176,"freememMachine":35168256,"freememHuman":"7%","cpus":[{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":467171300,"nice":36085700,"sys":452681300,"idle":3231117200,"irq":0}}],"date":"2019-03-05T20:53:37.240Z","dateHuman":"Tuesday 5th March 2019 23:53:37","dateDst":false,"devmode":false,"nodeVersion":"v8.12.0","homeyVersion":"2.0.4","homeyModelId":"homey1s","homeyModelName":"Homey (Early 2016)","timezone":"Europe/Moscow","wifiSsid":"Home","wifiAddress":"192.168.11.191:80","wifiMac":"6c:ad:f8:04:d5:f3"}
23:53:37 | Info subscribing now happens automatically, there is no need to manually call subscribe anymore
23:53:37 | Info Homekit server starting!

**Comment by sprut666666** [comment]
готово
