### ISSUE TITLE
Добавление новых устройств

### ISSUE THREAD

**Issue by Maxwell70** [sprut666666/com.sprut.homekit2#5]
Олег, Сергей! Большая просьба к вам добавить поддержку гаражных ворот и очистителя воздуха.
Гаражные ворота планируется использовать из нашего броадлинковского плагина (в случае добавления туда ворот - это тоже просьба) либо Роман обещал добавить ворота в свой плагин виртуальных девайсов.
Очиститель планируется использовать Mi Air Purifier из плагина Xiaomi Mi Home.
Заранее спасибо!

**Comment by sprut666666** [comment]
Требуется более подробное описание
