### ISSUE TITLE
нестабильность работы на 2.0.1

### ISSUE THREAD

**Issue by igerka** [sprut666666/com.sprut.homekit2#6]
изначально не добавлялись термостаты (виртуальный термостат от Романа) , потом после перезагрузки вообще мост не видит Homekit.

Логи:

rm","driverId":"switch","zone":"fc37305d-c833-4b68-a73c-56482f1433bc","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-23T21:37:47.487Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:52e177a7-410b-4e8c-ad14-6021e4fd7f16","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"dt3k6ezg121tjs3","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b21034000c230c230c23240c240c0c230d230c23240c0d230c230c23230c0c000163240c230c240c0c23240c240c0c230d23240c240c0c2300000000","false":"b20e3400240c0c230d23240c0d230c000163240c240c240c0c23240c240c0c230c23240c240c0c230c230d230c23240c240c0d230c230c2300000000"}}}
09:27:30 Success 52e177a7-410b-4e8c-ad14-6021e4fd7f16 is start added!
09:27:30 Info 52e177a7-410b-4e8c-ad14-6021e4fd7f16 - device found.
09:27:30 Success 4f5e8830-a63d-4887-95c8-af714c2bda95 is added!
09:27:30 Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"}}
09:27:30 Info Update: Подсветка кухня onoff: false new: true
09:27:30 Info Подсветка кухня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"4f5e8830-a63d-4887-95c8-af714c2bda95","name":"Подсветка кухня","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":true,"lastUpdated":"2019-01-24T06:24:40.199Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:4f5e8830-a63d-4887-95c8-af714c2bda95","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"5f78w6utdengvj2","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b200a8000b23240c0b240b230c000167230d230c0b240b230c23230d230c0b24230c0b240b24230c0b240b240b23230c0c230c230b24230c0c23230c0c230b240b000168230c230d0b230c230c23230c230d0b24230c0b240b23240c0b240b240b23240b0c230c230c23230c0c23230c0c240b230b000169220c240c0b240b230c23230d230c0c23230c0c230b24230c0c230c230b24230c0c230c230b24230c0b24230c0c230c230b0005dc","false":"b2063400230d230d0c240c240c24240d230d0c24230d0c240c24240d0c240c240c24240d0c240c240c24230d0c240c240c24240d0c00016a00000000"}}}
09:27:30 Success 4f5e8830-a63d-4887-95c8-af714c2bda95 is start added!
09:27:30 Info 4f5e8830-a63d-4887-95c8-af714c2bda95 - device found.
09:27:30 Success 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 is added!
09:27:30 Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"}}

**Comment by igerka** [comment]
Devices
Log
10:56:54	Info Update: Пол ванная TargetHeatingCoolingState: 0 new: 3
10:56:54	Info Пол ванная full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"1ea45725-3543-4df1-934e-a0171ba5a0af","name":"Пол ванная","driverUri":"homey:app:ru.notabene.virtualsensors","driverId":"thermostat","zone":"fc37305d-c833-4b68-a73c-56482f1433bc","icon":null,"iconObj":{"id":"958227b1f830cf10c0ae0c87f857057f","url":"/icon/958227b1f830cf10c0ae0c87f857057f/icon.svg"},"settings":{},"settingsObj":false,"class":"thermostat","virtualClass":null,"capabilities":["target_temperature","measure_temperature","thermostat_mode"],"capabilitiesObj":{"target_temperature":{"value":24.9,"lastUpdated":"2019-01-24T06:56:56.445Z","type":"number","getable":true,"setable":true,"title":"Target temperature","desc":null,"units":"°C","decimals":2,"min":4,"max":35,"chartType":"stepLine","id":"target_temperature","options":{}},"measure_temperature":{"value":27,"lastUpdated":"2019-01-24T08:34:15.466Z","type":"number","getable":true,"setable":false,"title":"Temperature","desc":null,"units":"°C","decimals":2,"chartType":"spline","id":"measure_temperature","options":{}},"thermostat_mode":{"value":"cool","lastUpdated":"2019-01-24T06:56:56.540Z","type":"enum","getable":true,"setable":true,"title":"Thermostat mode","desc":"Mode of the thermostat","units":null,"values":[{"id":"auto","title":"Automatic"},{"id":"heat","title":"Heat"},{"id":"cool","title":"Cool"},{"id":"off","title":"Off"}],"id":"thermostat_mode","options":{}}},"flags":[],"ui":{"components":[{"id":"thermostat","capabilities":["measure_temperature","target_temperature"]},{"id":"picker","capabilities":["thermostat_mode"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Set the temperature to 21 degrees","What is the average temperature at home?"],"images":[],"insights":[{"uri":"homey:device:1ea45725-3543-4df1-934e-a0171ba5a0af","id":"target_temperature","type":"number","title":"Target temperature","titleTrue":null,"titleFalse":null,"units":"°C"},{"uri":"homey:device:1ea45725-3543-4df1-934e-a0171ba5a0af","id":"measure_temperature","type":"number","title":"Temperature","titleTrue":null,"titleFalse":null,"units":"°C"}],"color":"#df2029","data":{"id":"91f04612745fd89168bc"}}
10:56:54	Success 1ea45725-3543-4df1-934e-a0171ba5a0af is start added!
10:49:48	Info Update: Спальня TargetHeatingCoolingState: 0 new: 3
10:49:48	Info Спальня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"e719c8e6-0c29-43f4-821b-3d4ed8972ba0","name":"Спальня","driverUri":"homey:app:ru.notabene.virtualsensors","driverId":"thermostat","zone":"24e740c8-8b76-4a0e-ade6-11fa5125c701","icon":null,"iconObj":{"id":"958227b1f830cf10c0ae0c87f857057f","url":"/icon/958227b1f830cf10c0ae0c87f857057f/icon.svg"},"settings":{},"settingsObj":false,"class":"thermostat","virtualClass":null,"capabilities":["target_temperature","measure_temperature","thermostat_mode"],"capabilitiesObj":{"target_temperature":{"value":19,"lastUpdated":"2019-01-23T21:40:06.748Z","type":"number","getable":true,"setable":true,"title":"Target temperature","desc":null,"units":"°C","decimals":2,"min":4,"max":35,"chartType":"stepLine","id":"target_temperature","options":{}},"measure_temperature":{"value":20,"lastUpdated":"2019-01-24T02:24:09.137Z","type":"number","getable":true,"setable":false,"title":"Temperature","desc":null,"units":"°C","decimals":2,"chartType":"spline","id":"measure_temperature","options":{}},"thermostat_mode":{"value":"cool","lastUpdated":"2019-01-23T22:13:52.576Z","type":"enum","getable":true,"setable":true,"title":"Thermostat mode","desc":"Mode of the thermostat","units":null,"values":[{"id":"auto","title":"Automatic"},{"id":"heat","title":"Heat"},{"id":"cool","title":"Cool"},{"id":"off","title":"Off"}],"id":"thermostat_mode","options":{}}},"flags":[],"ui":{"components":[{"id":"thermostat","capabilities":["measure_temperature","target_temperature"]},{"id":"picker","capabilities":["thermostat_mode"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Set the temperature to 21 degrees","What is the average temperature at home?"],"images":[],"insights":[{"uri":"homey:device:e719c8e6-0c29-43f4-821b-3d4ed8972ba0","id":"target_temperature","type":"number","title":"Target temperature","titleTrue":null,"titleFalse":null,"units":"°C"},{"uri":"homey:device:e719c8e6-0c29-43f4-821b-3d4ed8972ba0","id":"measure_temperature","type":"number","title":"Temperature","titleTrue":null,"titleFalse":null,"units":"°C"}],"color":"#df2029","data":{"id":"9d7a97b12a2f52159e37"}}
10:49:48	Success e719c8e6-0c29-43f4-821b-3d4ed8972ba0 is start added!
10:49:48	Info e719c8e6-0c29-43f4-821b-3d4ed8972ba0 - device found.
10:49:48	Success 7a8d2692-6a03-4c5e-93ee-7c4d16b57989 is added!
10:49:48	Info { "message": "Possible EventEmitter memory leak detected. 11 connect_error listeners added. Use emitter.setMaxListeners() to increase limit" }
10:49:48	Info { "message": "Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit" }
10:49:48	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
10:49:48	Info Прихожая подсветка full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"7a8d2692-6a03-4c5e-93ee-7c4d16b57989","name":"Прихожая подсветка","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"5e28fd80-edbb-4840-bdb0-a93c1ed0e720","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-24T08:00:29.163Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:7a8d2692-6a03-4c5e-93ee-7c4d16b57989","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"ggo3wykjuodtkd9","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b2009c0025110b2b0b2a0b2b0b2b0b2b0b2a0b2b0b2b0b2b0b2b2511251125120a2b25120b2a0b2b0b2b25110b2b0b2b251125110b00019225120b2a0b2b0b2b0b2b0a2b0b2b0b2b0b2b0a2b0b2b2511251225110a2c25110b2b0b2a0b2b25110b2b0b2b251125120a00019324120b2b0b2a0b2b0b2b0b2b0b2a0b2b0b2b0b2b0b2b2511251125120a2b25120a2b0b2b0b2b25110b2b0b2b251125110b0005dc000000000000000000000000","false":"b2009a000b2b0b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2a0c2a2610261125110b2b25110c2a0b2b0b2b25110b2b25110b2b0b2a0c00019225110b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2a0c2a0b2b2511261125110b2b25110b2b0b2b0b2a26110b2b25110b2b0b2a0b00019325110b2b0b2a0c2a0c2a0b2b0b2b0b2a0c2a0b2b0b2b2511261125110b2b25110b2b0b2b0b2b25110b2b25110b2b0b2b0a0005dc0000000000000000000000000000"}}}
10:49:48	Success 7a8d2692-6a03-4c5e-93ee-7c4d16b57989 is start added!
10:49:48	Info 7a8d2692-6a03-4c5e-93ee-7c4d16b57989 - device found.
10:49:48	Success 561334b5-d912-48cd-8c50-5155aae31a12 is added!
10:49:48	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
10:49:48	Info Гардероб свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"561334b5-d912-48cd-8c50-5155aae31a12","name":"Гардероб свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"6d7c87b2-4436-4fb9-9b26-d3e5bff64a89","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-24T08:13:20.030Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:561334b5-d912-48cd-8c50-5155aae31a12","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"ml5q4rk8jmzijm0","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b200d00025120a2b0b2b0b2b0b2b0b2a0b2b0b2b0b2b0b2b0b2a2512251125110b2b25110b2b0b2b0b2b25110b2b0b2b0a2b0b2b0b00019225110b2b0b2b0b2b0b2b0a2b0b2b0b2b0b2b0b2a0b2b2512251125110b2b25110b2b0b2b0b2b25110b2b0b2a0b2b0b2b0b00019225110b2b0b2b0b2b0a2b0b2b0b2b0b2b0b2b0b2b0b2a2512251125110b2b25110b2b0b2b0b2b25110b2b0a2b0b2b0b2b0b00019225110b2b0b2b0a2c0a2b0b2b0b2b0b2b0a2c0a2b0b2b2511261125110b2b25110b2b0b2b0a2b25120a2c0a2b0b2b0b2b0b0005dc0000000000000000","false":"b2009c0025110b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2a0c2a0b2b2511261125110b2a26110b2b0b2a0c2a25110b2b0b2b0b2b25110b00019126110b2a0c2a0b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2a2512251125110b2b25110c2a0b2b0b2a26110b2b0b2a0b2b25110b00019226100c2a0b2b0b2b0b2a0c2a0b2b0b2b0b2b0b2b0b2a2610261125110b2b25110b2b0b2a0c2a26110b2a0b2b0b2b25110b0005dc000000000000000000000000"}}}
10:49:48	Success 561334b5-d912-48cd-8c50-5155aae31a12 is start added!
10:49:48	Info 561334b5-d912-48cd-8c50-5155aae31a12 - device found.
10:49:48	Success 86041209-87db-4690-be25-286ef5a358ca is added!
10:49:48	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
10:49:48	Info прихожая свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"86041209-87db-4690-be25-286ef5a358ca","name":"прихожая свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"5e28fd80-edbb-4840-bdb0-a93c1ed0e720","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-22T21:54:58.879Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:86041209-87db-4690-be25-286ef5a358ca","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"9dte9w0urmcokfp","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b210340025120b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0c2c2612261225120b2c25120b2c0b2c0b2c0b2c261225120b2c25120b00019400000000","false":"b20c340025120b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c0b2c2512251225130b2c25130b2c0b2c0b2c0b2c2512251225120b2c0b00019400000000"}}}
10:49:48	Success 86041209-87db-4690-be25-286ef5a358ca is start added!
10:49:48	Info 86041209-87db-4690-be25-286ef5a358ca - device found.
10:49:48	Success 52e177a7-410b-4e8c-ad14-6021e4fd7f16 is added!
10:49:48	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
10:49:48	Info Вентиляция ванная full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"52e177a7-410b-4e8c-ad14-6021e4fd7f16","name":"Вентиляция ванная","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"fc37305d-c833-4b68-a73c-56482f1433bc","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-24T07:42:38.181Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:52e177a7-410b-4e8c-ad14-6021e4fd7f16","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"dt3k6ezg121tjs3","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b21034000c230c230c23240c240c0c230d230c23240c0d230c230c23230c0c000163240c230c240c0c23240c240c0c230d23240c240c0c2300000000","false":"b20e3400240c0c230d23240c0d230c000163240c240c240c0c23240c240c0c230c23240c240c0c230c230d230c23240c240c0d230c230c2300000000"}}}
10:49:48	Success 52e177a7-410b-4e8c-ad14-6021e4fd7f16 is start added!
10:49:48	Info 52e177a7-410b-4e8c-ad14-6021e4fd7f16 - device found.
10:49:47	Success 4f5e8830-a63d-4887-95c8-af714c2bda95 is added!
10:49:47	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"}}
10:49:47	Info Update: Подсветка кухня onoff: false new: true
10:49:47	Info Подсветка кухня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"4f5e8830-a63d-4887-95c8-af714c2bda95","name":"Подсветка кухня","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":true,"lastUpdated":"2019-01-24T06:24:40.199Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:4f5e8830-a63d-4887-95c8-af714c2bda95","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"5f78w6utdengvj2","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b200a8000b23240c0b240b230c000167230d230c0b240b230c23230d230c0b24230c0b240b24230c0b240b240b23230c0c230c230b24230c0c23230c0c230b240b000168230c230d0b230c230c23230c230d0b24230c0b240b23240c0b240b240b23240b0c230c230c23230c0c23230c0c240b230b000169220c240c0b240b230c23230d230c0c23230c0c230b24230c0c230c230b24230c0c230c230b24230c0b24230c0c230c230b0005dc","false":"b2063400230d230d0c240c240c24240d230d0c24230d0c240c24240d0c240c240c24240d0c240c240c24230d0c240c240c24240d0c00016a00000000"}}}
10:49:47	Success 4f5e8830-a63d-4887-95c8-af714c2bda95 is start added!
10:49:47	Info 4f5e8830-a63d-4887-95c8-af714c2bda95 - device found.
10:49:47	Success 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 is added!
10:49:47	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"}}
10:49:47	Info Update: Бар свет onoff: false new: true
10:49:47	Info Бар свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8","name":"Бар свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":true,"lastUpdated":"2019-01-24T00:40:02.767Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"lhiad10bn0nxszr","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b20d3400230d0c24230d0c24230d230d230d0c24240c0c240c24230d0c240c240c24230d0c240c240c24240c0c240c240c24230d0c00016700000000","false":"b20f34000c24230d0c240c240c24240d0c240c24230d0c240c000168230c0c24240d0c24240d240d240d0c24230d0c240c24240d0c240c2400000000"}}}
10:49:47	Success 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 is start added!
10:49:47	Info 0c8ecf9e-3c4b-4fc9-b6ec-af313fd653d8 - device found.
10:49:47	Success 484ba688-3ab5-4877-b692-0c745dec494a is added!
10:49:47	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
10:49:47	Info Кухня свет full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"484ba688-3ab5-4877-b692-0c745dec494a","name":"Кухня свет","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-22T21:55:53.332Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:484ba688-3ab5-4877-b692-0c745dec494a","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"s0auo7gvs16p9hu","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b2093400230d0c240c24230d0c240c240c24230d0c240c240c24240d0c24240d0c240c240c000167230d0c24230d0c24240d240d230d0c2400000000","false":"b2153400240c240c240c0c23240c0d230d23240c0d230d230c23240c0c240c230d23240c250c0c230d240c230d000167240c0c23240c0c2300000000"}}}
10:49:47	Success 484ba688-3ab5-4877-b692-0c745dec494a is start added!
10:49:47	Info 484ba688-3ab5-4877-b692-0c745dec494a - device found.
10:49:47	Success 28f0f423-6ea0-40fa-80dd-088bec716cc7 is added!
10:49:47	Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":false,"ev":true,"description":"On","format":"bool"}}
10:49:47	Info Подсветка спальня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"28f0f423-6ea0-40fa-80dd-088bec716cc7","name":"Подсветка спальня","driverUri":"homey:app:com.broadlink.rm","driverId":"switch","zone":"24e740c8-8b76-4a0e-ade6-11fa5125c701","icon":null,"iconObj":{"id":"7974b3f82ffff1ce0e15012934a7ebd4","url":"/icon/7974b3f82ffff1ce0e15012934a7ebd4/icon.svg"},"settings":{},"settingsObj":false,"class":"heater","virtualClass":null,"capabilities":["onoff"],"capabilitiesObj":{"onoff":{"value":false,"lastUpdated":"2019-01-23T22:49:31.410Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}}},"flags":[],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:28f0f423-6ea0-40fa-80dd-088bec716cc7","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#df20c9","data":{"id":"u8p6xp0h9rfn27k","deviceId":"0d:43:b4:da:27:6b","commands":{"true":"b21a3400240c240c240c0c23240c240c0d230d23240c240c0c230c230c230c23240c240c0d230c230c23240c0c23240c0c230c230d00016400000000","false":"b20f3400240c240c240c0c23240c240c0d230d23240c240c0c230c230c230c23240c240c0d230c230c23240c240c0c230c230d230c00016300000000"}}}
10:49:47	Success 28f0f423-6ea0-40fa-80dd-088bec716cc7 is start added!

**Comment by sprut666666** [comment]
3.0.2
