### ISSUE TITLE
корректировки, прошивка 2.0.1

### ISSUE THREAD

**Issue by igerka** [sprut666666/com.sprut.homekit2#8]
1. любой виртуальный девайс (шторы, термостаты, замок) "не фиксируется" в настройках плагина при нажатии "ADD group" но в ките появлется - скрин на скрепке

![img_2808](https://user-images.githubusercontent.com/38116628/51681810-69402600-1fee-11e9-907e-91343391ead3.JPG)

2.  раньше в V1.5 в именах - не дублировалось название комнаты и устройства - например если термостат назван "ванная", то в имени будет "ванная ванная"- скрин на скрепке

![img_2810](https://user-images.githubusercontent.com/38116628/51681777-5299cf00-1fee-11e9-953e-beedefd7169e.JPG)

3. при очередной перезагрузке Колобка ушел мост в офлайн "нет ответа" ни локально ни удаленно. Очередная перезагрузка колобка/плагина не помогает. - скрин на скрепке

![img_2812](https://user-images.githubusercontent.com/38116628/51681798-63e2db80-1fee-11e9-86b8-e220bee735c1.JPG)

Лог с моента перезгрузки (мост китом не видится):

Devices
Log
15:28:05 Info State in HomeKit: {"thermostat_mode":true,"TargetHeatingCoolingState":{"type":"00000033-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":2,"ev":true,"description":"Target Heating Cooling State","format":"uint8","valid-values":[0,1,2,3]},"CurrentHeatingCoolingState":{"type":"0000000F-0000-1000-8000-0026BB765291","iid":8,"perms":["pr","ev"],"value":2,"ev":true,"description":"Current Heating Cooling State","format":"uint8","valid-values":[0,1,2]},"target_temperature":{"type":"00000035-0000-1000-8000-0026BB765291","iid":9,"perms":["pr","pw","ev"],"value":19,"ev":true,"description":"Target Temperature","format":"float","unit":"celsius","minValue":4,"maxValue":35,"minStep":0.1},"measure_temperature":{"type":"00000011-0000-1000-8000-0026BB765291","iid":11,"perms":["pr","ev"],"value":21,"ev":true,"description":"Current Temperature","format":"float","unit":"celsius","minValue":-100,"maxValue":100,"minStep":0.01}}
15:28:05 Info Update: Кухня measure_temperature: -100 new: 21
15:28:05 Info Update: Кухня target_temperature: 4 new: 19
15:28:05 Info Update: Кухня CurrentHeatingCoolingState: 0 new: 2
15:28:05 Info Update: Кухня TargetHeatingCoolingState: 0 new: 2
15:28:05 Info Кухня full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"417102be-6928-4bd5-8cd3-ab3aa3af7ae4","name":"Кухня","driverUri":"homey:app:ru.notabene.virtualsensors","driverId":"thermostat","zone":"bc052b5c-74f6-41aa-bafd-b99a6d4b3a1d","icon":null,"iconObj":{"id":"958227b1f830cf10c0ae0c87f857057f","url":"/icon/958227b1f830cf10c0ae0c87f857057f/icon.svg"},"settings":{},"settingsObj":false,"class":"thermostat","virtualClass":null,"capabilities":["target_temperature","measure_temperature","thermostat_mode"],"capabilitiesObj":{"target_temperature":{"value":19,"lastUpdated":"2019-01-24T11:29:33.310Z","type":"number","getable":true,"setable":true,"title":"Target temperature","desc":null,"units":"°C","decimals":2,"min":4,"max":35,"chartType":"stepLine","id":"target_temperature","options":{}},"measure_temperature":{"value":21,"lastUpdated":"2019-01-24T07:04:08.749Z","type":"number","getable":true,"setable":false,"title":"Temperature","desc":null,"units":"°C","decimals":2,"chartType":"spline","id":"measure_temperature","options":{}},"thermostat_mode":{"value":"cool","lastUpdated":"2019-01-23T21:35:01.504Z","type":"enum","getable":true,"setable":true,"title":"Thermostat mode","desc":"Mode of the thermostat","units":null,"values":[{"id":"auto","title":"Automatic"},{"id":"heat","title":"Heat"},{"id":"cool","title":"Cool"},{"id":"off","title":"Off"}],"id":"thermostat_mode","options":{}}},"flags":[],"ui":{"components":[{"id":"thermostat","capabilities":["measure_temperature","target_temperature"]},{"id":"picker","capabilities":["thermostat_mode"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Set the temperature to 21 degrees","What is the average temperature at home?"],"images":[],"insights":[{"uri":"homey:device:417102be-6928-4bd5-8cd3-ab3aa3af7ae4","id":"target_temperature","type":"number","title":"Target temperature","titleTrue":null,"titleFalse":null,"units":"°C"},{"uri":"homey:device:417102be-6928-4bd5-8cd3-ab3aa3af7ae4","id":"measure_temperature","type":"number","title":"Temperature","titleTrue":null,"titleFalse":null,"units":"°C"}],"color":"#df2029","data":{"id":"396f0c635bff18f33bfe"}}
15:28:05 Success 417102be-6928-4bd5-8cd3-ab3aa3af7ae4 is start added!
15:28:05 Info 417102be-6928-4bd5-8cd3-ab3aa3af7ae4 - device found.
15:28:05 Success c38fbf98-9e33-47ef-8ba8-b6493384b658 is added!

15:28:05 Info State in HomeKit: {"onoff":{"type":"00000025-0000-1000-8000-0026BB765291","iid":7,"perms":["pr","pw","ev"],"value":true,"ev":true,"description":"On","format":"bool"},"dim":{"type":"00000008-0000-1000-8000-0026BB765291","iid":8,"perms":["pr","pw","ev"],"value":5,"ev":true,"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"light_hue":{"type":"00000013-0000-1000-8000-0026BB765291","iid":9,"perms":["pr","pw","ev"],"value":310,"ev":true,"description":"Hue","format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1},"light_saturation":{"type":"0000002F-0000-1000-8000-0026BB765291","iid":10,"perms":["pr","pw","ev"],"value":94,"ev":true,"description":"Saturation","format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},"light_temperature":{"type":"000000CE-0000-1000-8000-0026BB765291","iid":11,"perms":["pr","pw","ev"],"value":140,"ev":true,"description":"Color Temperature","format":"uint32","minValue":140,"maxValue":500,"minStep":1}}
15:28:05 Info Update: LED прихожая light_saturation: 0 new: 94
15:28:05 Info Update: LED прихожая light_hue: 0 new: 310
15:28:05 Info Update: LED прихожая dim: 0 new: 5
15:28:05 Info Update: LED прихожая onoff: false new: true
15:28:05 Info LED прихожая full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"c38fbf98-9e33-47ef-8ba8-b6493384b658","name":"LED прихожая","driverUri":"homey:app:com.gledopto","driverId":"gledopto_rgb","zone":"5e28fd80-edbb-4840-bdb0-a93c1ed0e720","icon":null,"iconObj":{"id":"f7f4cc0627f6d0bbf205039f8f0af9ce","url":"/icon/f7f4cc0627f6d0bbf205039f8f0af9ce/icon.svg"},"settings":{"zb_profile_id":"49246","zb_device_id":"528","zb_ieee_addr":"0x00124b0019a81d89","zb_product_id":"GLEDOPTO","zb_manufacturer_name":"GLEDOPTO","transition_time":1},"settingsObj":true,"class":"light","virtualClass":null,"capabilities":["onoff","dim","light_hue","light_saturation","light_temperature","light_mode"],"capabilitiesObj":{"onoff":{"value":true,"lastUpdated":"2019-01-23T16:48:01.893Z","type":"boolean","getable":true,"setable":true,"title":"Turned on","desc":null,"units":null,"id":"onoff","options":{}},"dim":{"value":0.05,"lastUpdated":"2019-01-23T16:48:01.636Z","type":"number","getable":true,"setable":true,"title":"Dim level","desc":null,"units":"%","decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"dim","options":{}},"light_hue":{"value":0.8611111111111112,"lastUpdated":"2019-01-23T16:48:17.158Z","type":"number","getable":true,"setable":true,"title":"Hue","desc":null,"units":null,"decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"light_hue","options":{}},"light_saturation":{"value":0.94,"lastUpdated":"2019-01-23T16:48:17.140Z","type":"number","getable":true,"setable":true,"title":"Color Saturation","desc":null,"units":null,"decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"light_saturation","options":{}},"light_temperature":{"value":null,"lastUpdated":"2019-01-24T13:27:29.723Z","type":"number","getable":true,"setable":true,"title":"Color Temperature","desc":null,"units":null,"decimals":2,"min":0,"max":1,"chartType":"stepLine","id":"light_temperature","options":{}},"light_mode":{"value":"color","lastUpdated":"2019-01-23T16:39:05.

309Z","type":"enum","getable":true,"setable":true,"title":"Light mode","desc":"Switch between Color or Temperature mode","units":null,"values":[{"id":"color","title":"Color"},{"id":"temperature","title":"Temperature"}],"id":"light_mode","options":{}}},"flags":["zigbee"],"ui":{"quickAction":"onoff","components":[{"id":"toggle","capabilities":["onoff"]},{"id":"slider","capabilities":["dim"]},{"id":"color","capabilities":["light_hue","light_saturation","light_temperature","light_mode"]}],"componentsStartAt":1},"ready":true,"available":true,"repair":false,"unpair":true,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights","Dim all lights to 50%","Set My Light to full brightness","Turn all lights to blue","Turn My Light to pink","Turn all lights to warm white","Turn My Light to cool white"],"images":[],"insights":[{"uri":"homey:device:c38fbf98-9e33-47ef-8ba8-b6493384b658","id":"onoff","type":"boolean","title":"Turned on","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#2053df","data":{"token":"64ff919c-31e1-4e17-8a39-ecc145710958"}}
15:28:05 Success c38fbf98-9e33-47ef-8ba8-b6493384b658 is start added!
15:28:05 Info c38fbf98-9e33-47ef-8ba8-b6493384b658 - device found.
15:28:05 Success Server config done.
15:28:04 Success {"bootId":"733075f6-481b-404c-8c95-9e7b3b892a17","cloudId":"5aa90e5c05eff5043791a6c7","hostname":"Homey","platform":"linux","release":"4.14.15-g81f15bab94","arch":"arm","uptime":207,"loadavg":[4.30810546875,1.97119140625,0.7685546875],"totalmem":511922176,"freememMachine":10035200,"freememHuman":"2%","cpus":[{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":801500,"nice":363200,"sys":796700,"idle":89900,"irq":0}}],"date":"2019-01-24T13:28:04.781Z","dateHuman":"Thursday 24th January 2019 15:28:04","dateDst":false,"devmode":false,"nodeVersion":"v8.12.0","homeyVersion":"2.0.1","homeyModelId":"homey2s","homeyModelName":"Homey (Early 2018)","timezone":"Europe/Kaliningrad","wifiSsid":"German_2Ghz","wifiAddress":"192.168.1.18:80","wifiMac":"2c:6b:7d:14:71:4f"}
15:28:04 Info subscribing now happens automatically, there is no need to manually call subscribe anymore
15:28:04 Info Homekit server starting!

**Comment by sprut666666** [comment]
3.0.4
