### ISSUE TITLE
Проводной выключатель Aqara

### ISSUE THREAD

**Issue by permadm** [sprut666666/com.sprut.homekit2#9]
Проводной двойной выключатель Aqara подключенный через плагин MiHomey не верно добавляется в кит 
![telegram-cloud-file-2-255431959-267502-731441860779007738](https://user-images.githubusercontent.com/23650010/51804068-dd442d80-227d-11e9-8585-8b3510a566ac.jpg)
![telegram-cloud-file-2-257901679-82911--8008540817760040427](https://user-images.githubusercontent.com/23650010/51804076-ef25d080-227d-11e9-85b7-7521490d6b10.jpg)

Info Кухня Выключатель full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"bd93cfa8-896b-49a9-a244-a1ab16bbe70c","name":"Кухня Выключатель","driverUri":"homey:app:com.maxmudjon.mihomey","driverId":"ctrl_neutral2","zone":"2ab5a003-0120-4c01-80f2-a237dcf4ba14","icon":null,"iconObj":{"id":"852bd4b395dcc2428a3a81fced0c195d","url":"/icon/852bd4b395dcc2428a3a81fced0c195d/icon.svg"},"settings":{"deviceSid":"158d000153b3ba","deviceFromGatewaySid":"f0b429cc224a","deviceModelName":"lumi.ctrl_neutral2","deviceModelCodeName":"QBKG03LM"},"settingsObj":true,"class":"socket","virtualClass":null,"capabilities":["onoff.1","onoff.2"],"capabilitiesObj":{"onoff.1":{"value":false,"lastUpdated":"2019-01-25T16:37:30.062Z","type":"boolean","getable":true,"setable":true,"title":"Left On/Off","desc":null,"units":null,"id":"onoff.1","options":{"title":{"en":"Left On/Off"},"greyout":false}},"onoff.2":{"value":true,"lastUpdated":"2019-01-27T14:26:21.652Z","type":"boolean","getable":true,"setable":true,"title":"Right On/Off","desc":null,"units":null,"id":"onoff.2","options":{"title":{"en":"Right On/Off"},"greyout":false}}},"flags":[],"ui":{"quickAction":"onoff.1","components":[{"id":"toggle","capabilities":["onoff.1","onoff.2"]}],"componentsStartAt":0},"ready":true,"available":true,"repair":false,"unpair":false,"speechExamples":["Turn all lights on","Turn off all devices","Toggle all lights","Turn all lights on","Turn off all devices","Toggle all lights"],"images":[],"insights":[{"uri":"homey:device:bd93cfa8-896b-49a9-a244-a1ab16bbe70c","id":"onoff.1","type":"boolean","title":"Left On/Off","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null},{"uri":"homey:device:bd93cfa8-896b-49a9-a244-a1ab16bbe70c","id":"onoff.2","type":"boolean","title":"Right On/Off","titleTrue":"Turned on","titleFalse":"Turned off","units":null,"decimals":null}],"color":"#FF6700","data":{"sid":"158d000153b3ba"}}
21:46:54 Success bd93cfa8-896b-49a9-a244-a1ab16bbe70c is start added!

**Comment by sprut666666** [comment]
готово
